FileVersion = 1
Unlocked = ["rlCImGuiBeef", "raylib-aseprite-beef", "corlib", "BJSON"]

[Workspace]
StartupProject = "Leaf"

[[Workspace.DistinctOptions]]
Filter = ""

[Projects]
Leaf = {Path = "."}
raylib-beef = "*"
ImGui = "*"
rlCImGuiBeef = "*"
raylib-aseprite-beef = "*"
TinySoundFontBeef = {Path = "../../../Software/Beef/BeefLibs/TinySoundFontBeef"}
Jolt = {Path = "../../../Software/Beef/BeefLibs/C2Beef-Binding-Generator/Jolt"}

[WorkspaceFolders]
Libs = ["corlib", "raylib-beef", "ImGui", "rlCImGuiBeef", "raylib-aseprite-beef", "TinySoundFontBeef", "BJSON", "Jolt", "MiniZ"]

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
