FileVersion = 1

[Project]
Name = "Leaf"
StartupObject = "Leaf.Program"

[Dependencies]
corlib = "*"
corlib = "*"
TinySoundFontBeef = "*"
raylib-beef = "*"
BJSON = "*"
ImGui = "*"
Jolt = "*"
LuaTinker = "*"
rlCImGuiBeef = "*"
raylib-aseprite-beef = "*"

[Configs.Debug.Win64]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
TargetName = "$(ProjectName)_d"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[Configs.Debug.wasm32]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
TargetName = "leaf"
OtherLinkFlags = "$(LinkFlags) -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s USE_GLFW=3"
DebugCommand = ""

[Configs.Debug.Win32]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[Configs.Release.wasm32]
OtherLinkFlags = "$(LinkFlags) -o index.html --use-preload-plugins -DPLATFORM_WEB --shell-file D:/Software/Beef/wasm/shell.html -s ASYNCIFY=1 -O2 -g4 --profiling -v -s FORCE_FILESYSTEM -s STACK_SIZE=16777216 -s TOTAL_MEMORY=134217728 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1"

[Configs.Release.Win64]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[Configs.Paranoid.Win64]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[Configs.Test.Win64]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[[ProjectFolder.Items]]
Type = "IgnoreSource"
Name = "Tweenie.bf"

[[ProjectFolder.Items]]
Type = "AutoFolder"
Name = "Audio"

[[ProjectFolder.Items.Items]]
Type = "IgnoreSource"
Name = "MidiReader.bf"

[[ProjectFolder.Items]]
Type = "AutoFolder"
Name = "Scenes"

[[ProjectFolder.Items.Items]]
Type = "IgnoreSource"
Name = "SceneNetworking - Copy.bf"
